# Generated by Django 5.0.6 on 2024-05-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_university_required_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='required_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='tests.category'),
        ),
        migrations.AlterField(
            model_name='university',
            name='required_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='tests.subject'),
        ),
    ]
