# Generated by Django 4.2 on 2024-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='rating',
            field=models.CharField(max_length=255),
        ),
    ]
