# Generated by Django 5.0.6 on 2024-05-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_university_required_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='required_category',
        ),
        migrations.RemoveField(
            model_name='university',
            name='required_points',
        ),
        migrations.RemoveField(
            model_name='university',
            name='required_subject',
        ),
    ]
