# Generated by Django 5.0.6 on 2024-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_university_required_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='professions',
            field=models.ManyToManyField(related_name='universities', to='tests.profession'),
        ),
    ]
