# Generated by Django 5.0.6 on 2024-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_university_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='categories',
            field=models.ManyToManyField(related_name='universities', to='tests.category'),
        ),
    ]
