# Generated by Django 5.0.6 on 2024-05-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_university_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='categories',
        ),
    ]
