# Generated by Django 5.0.6 on 2024-05-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_subjecttestresult_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
    ]
