# Generated by Django 5.0.6 on 2024-05-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_remove_testresult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubjectTestResult',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
