# Generated by Django 5.0.6 on 2024-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_testresult_category_remove_testresult_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='contract',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='mission_and_goals',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='threshold_ort',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
