# Generated by Django 5.0.6 on 2024-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_alter_answer_category_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='mission_and_goals',
            field=models.TextField(blank=True, null=True, verbose_name='Миссия и цели'),
        ),
    ]
