# Generated by Django 5.0.6 on 2024-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_university_added_by_alter_university_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='categories',
            field=models.ManyToManyField(related_name='universities', to='tests.category'),
        ),
        migrations.AlterField(
            model_name='university',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='university',
            name='language_of_instruction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='professions',
            field=models.ManyToManyField(related_name='universities', to='tests.profession'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='scholarship',
            field=models.IntegerField(verbose_name='Стипендия (200 орт/баллы)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='threshold_ort',
            field=models.IntegerField(verbose_name='Пароговый орт на поступление (110 орт/баллы)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(),
        ),
    ]
