# Generated by Django 5.0.6 on 2024-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_alter_university_address_alter_university_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='university',
            name='categories',
            field=models.ManyToManyField(related_name='universities', to='tests.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='university',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.EmailField(max_length=125, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='university',
            name='language_of_instruction',
            field=models.CharField(max_length=255, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='professions',
            field=models.ManyToManyField(related_name='universities', to='tests.profession', verbose_name='Профессий'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rating',
            field=models.CharField(max_length=255, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='university',
            name='scholarship',
            field=models.CharField(max_length=255, verbose_name='Стипендия'),
        ),
        migrations.AlterField(
            model_name='university',
            name='threshold_ort',
            field=models.CharField(max_length=255, verbose_name='Пароговый балл орт'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(max_length=255, verbose_name='Веб сайт'),
        ),
    ]
