# Generated by Django 5.0.6 on 2024-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_university_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='budget',
            field=models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], max_length=255, verbose_name='Бюджет'),
        ),
    ]
