# Generated by Django 5.0.6 on 2024-05-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_alter_university_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='profession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='professions/'),
        ),
        migrations.AlterField(
            model_name='subjectanswer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильный'),
        ),
    ]
