# Generated by Django 5.0.6 on 2024-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_profession_description_profession_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='universities',
            field=models.ManyToManyField(related_name='related_professions', to='tests.university', verbose_name='Университеты'),
        ),
        migrations.AlterField(
            model_name='university',
            name='professions',
            field=models.ManyToManyField(related_name='related_universities', to='tests.profession', verbose_name='Профессий'),
        ),
    ]
