# Generated by Django 5.0.6 on 2024-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_profession_universities_alter_university_professions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='universities',
        ),
        migrations.AlterField(
            model_name='university',
            name='professions',
            field=models.ManyToManyField(related_name='universities', to='tests.profession', verbose_name='Профессий'),
        ),
    ]
