# Generated by Django 5.0.6 on 2024-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_universities',
            field=models.BooleanField(default=False, verbose_name='Может добавлять университеты'),
        ),
    ]
