# Generated by Django 5.0.6 on 2024-05-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_can_add_universities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_add_universities',
        ),
    ]
