# Generated by Django 5.0.6 on 2024-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_can_add_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_university',
            field=models.BooleanField(default=False, verbose_name='Может добавлять университеты'),
        ),
    ]
